apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.airflow.dags.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flowchart.labels" . | nindent 4 }}
data:
{{- $root := . }}            # top-level ctx
{{- range $path := .Values.airflow.dags.files }}
  {{ base $path }}: |-
{{ $root.Files.Get $path | indent 4 }}
{{- end }}
