apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowchart.fullname" .}}-postgres-data
  namespace: {{ .Values.namespace }}
  labels:
{{ include "flowchart.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresData.port}}
      targetPort: {{ .Values.postgresData.port}}
      name: postgres
  selector:
{{ include "flowchart.selectorLabels" . | nindent 4}}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "flowchart.fullname" .}}-postgres-data
  labels:
{{ include "flowchart.labels" . | nindent 4}}
spec:
  serviceName: {{ include "flowchart.fullname" .}}-postgres-data
  replicas: 1
  selector:
    matchLabels:
      {{- include "flowchart.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "flowchart.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: postgres-data
          image: "{{ .Values.postgresData.image.repository }}:{{ .Values.postgresData.image.tag }}"
          imagePullPolicy: {{ .Values.postgresData.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.postgresData.port}}
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "flowchart.fullname" .}}-secrets
                  key: POSTGRES_DATA_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "flowchart.fullname" .}}-secrets
                  key: POSTGRES_DATA_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "flowchart.fullname" .}}-secrets
                  key: POSTGRES_DATA_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresData.persistence.size}}
