---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowchart.fullname" .}}-postgres-airflow
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "flowchart.labels" . | nindent 4}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresAirflow.port }}
      targetPort: {{ .Values.postgresAirflow.port}}
      name: postgres
  selector:
    {{- include "flowchart.selectorLabels" . | nindent 4}}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "flowchart.fullname" .}}-postgres-airflow
  labels:
    {{- include "flowchart.labels" . | nindent 4}}
spec:
  serviceName: {{ include "flowchart.fullname" .}}-postgres-airflow
  replicas: 1
  selector:
    matchLabels:
      {{- include "flowchart.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "flowchart.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: postgres-airflow
          image: "{{ .Values.postgresAirflow.image.repository}}:{{ .Values.postgresAirflow.image.tag}}"
          imagePullPolicy: {{ .Values.postgresAirflow.image.pullPolicy}}
          ports:
            - containerPort: {{ .Values.postgresAirflow.port}}
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresAirflow.db}}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresAirflow.user}}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresAirflow.password}}"
          volumeMounts:
            - name: postgres-airflow-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-airflow-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresAirflow.persistence.size}}
