apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowchart.fullname" .}}-secrets
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "flowchart.labels" . | nindent 4}}
type: Opaque
stringData:
  FERNET_KEY: {{ .Values.secrets.fernetKey | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  POSTGRES_DATA_USER: {{ .Values.secrets.postgresDataUser | quote }}
  POSTGRES_DATA_PASSWORD: {{ .Values.secrets.postgresDataPassword | quote }}
  POSTGRES_DATA_DB: {{ .Values.secrets.postgresDataDb | quote }}
  GRAFANA_USER: {{ .Values.secrets.grafanaUser | quote }}
  GRAFANA_PASSWORD: {{ .Values.secrets.grafanaPassword | quote }}
