version: "3"

tasks:
  remove-cache:
    cmds:
      - find . -type d -name "__pycache__" | xargs rm -rf 2>/dev/null || true
      - find . -type d -name ".ruff_cache" | xargs rm -rf 2>/dev/null || true
    desc: "Removes cache produced by Python and Ruff."
