version: "3"

vars:
  SHA:
    sh: git rev-parse --short HEAD
  AIRFLOW_IMAGE: airflow:{{ .SHA}}

tasks:
  remove-cache:
    cmds:
      - find . -type d -name "__pycache__" | xargs rm -rf 2>/dev/null || true
      - find . -type d -name ".ruff_cache" | xargs rm -rf 2>/dev/null || true
    desc: "Removes cache produced by Python and Ruff."

  build-airflow-image:
    cmds:
      - docker build --tag {{ .AIRFLOW_IMAGE}} -f docker/Dockerfile .
    desc: "[DEPENDENCY]: Builds the Airflow image for the compose task."

  compose-up:
    deps: [build-airflow-image]
    cmds:
      - AIRFLOW_IMAGE={{ .AIRFLOW_IMAGE}} docker compose -f docker/docker-compose.yaml --env-file=.env up --build -d
    desc: "Starts the Airflow stack."

  compose-down:
    cmds:
      - AIRFLOW_IMAGE={{ .AIRFLOW_IMAGE}} docker compose -f docker/docker-compose.yaml --env-file=.env down
    desc: "Stops the Airflow stack."

  compose-reset:
    cmds:
      - AIRFLOW_IMAGE={{ .AIRFLOW_IMAGE}} docker compose -f docker/docker-compose.yaml --env-file=.env down -v --remove-orphans

  docker-clean:
    cmds:
      - docker stop $(docker ps -aq) || true
      - docker rm $(docker ps -aq) || true
    desc: "[WARNING]: Kills all the containers."
