apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sts.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.svc.name }}
  replicas: {{ .Values.sts.replicas }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 472  # perm-errors
      containers:
        - name: grafana
          image: {{ .Values.sts.image }}
          imagePullPolicy: {{ .Values.sts.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: GRAFANA_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: GRAFANA_PASSWORD
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.sts.storageClassName }}
        storageClassName: {{ .Values.sts.storageClassName }}
        {{- end}}
        resources:
          requests:
            storage: {{ .Values.sts.storage }}
