x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE}
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "admin:admin"
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "true"
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
    AIRFLOW__CORE__INTERNAL_API_URL: "http://airflow-apiserver:8080"
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__API__SECRET_KEY: ${SECRET_KEY}
    AIRFLOW__API_AUTH__JWT_SECRET: ${JWT_SECRET}
    AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: ${JWT_SECRET}
    # make sure POSTGRES_* variables are not overriden by Airflow's own postgres ENV vars:
    BTCFLOW_POSTGRES_HOST: postgres-data
    BTCFLOW_POSTGRES_USER: ${POSTGRES_DATA_USER}
    BTCFLOW_POSTGRES_PASSWORD: ${POSTGRES_DATA_PASSWORD}
    BTCFLOW_POSTGRES_DB: ${POSTGRES_DATA_DB}
  volumes:
    - ../dags:/opt/airflow/dags
    - ../data:/opt/airflow/data
    # - ../logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy
    postgres-data:
      condition: service_healthy
    airflow-init:
      condition: service_completed_successfully

services:
  # this service holds the Airflow metadata:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 3s
      retries: 3
  # this service holds Bitcoin ETL data (separate from Airflow's metadata DB):
  postgres-data:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_DATA_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATA_DB}
    ports:
      # expose to 5433 so it doesn't conflict if local Postgres is running:
      - "5433:5432"
    # VolumeType --mount:
    volumes:
      - postgres_mount:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_DATA_USER}"]
      interval: 3s
      retries: 3

  # separate from x-airflow-common (doesn't get circular `depends_on` itself):
  airflow-init:
    image: ${AIRFLOW_IMAGE}
    command: ["airflow", "db", "migrate"]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  airflow-apiserver:
    <<: *airflow-common
    command: ["airflow", "api-server"]
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: ["airflow", "scheduler"]
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: ["airflow", "dag-processor"]
    restart: always

# Adds "docker_" as prefix:
volumes:
  postgres_mount:

# [If containers are down]: export .env &&:
# ⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺
# $ docker run -d --name=postgres-data \
#   --mount type=volume,source=docker_postgres_mount,destination=//var/lib/postgresql/data \
#   -e POSTGRES_USER=${POSTGRES_DATA_USER} \
#   -e POSTGRES_PASSWORD=${POSTGRES_DATA_PASSWORD} \
#   -e POSTGRES_DB=${POSTGRES_DATA_DB} \
#   postgres:15-alpine \
# && docker exec -it postgres-data \
# psql -U ${POSTGRES_DATA_USER} -d ${POSTGRES_DATA_DB}
# ⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺⸺
# to visualize the transformed data is the mempool_stats table.
