defaults:
  - hydra-settings
  - db: postgres
  - _self_

api:
  base_url: "https://mempool.space/api"
  timeout: 10

dag:
  id: "mempool_etl"
  schedule: "*/1 * * * *"
  catchup: false
  max_active_runs: 1
  tags:
    - bitcoin
    - mempool
    - etl
  retries: 3
  retry_delay_seconds: 60
