name: docker-build-reusable

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: validate-environment-input
        run: |
          if [ "${{ inputs.environment }}" != "development" ] && [ "${{ inputs.environment }}" != "staging" ]; then
            echo "Invalid environment: ${{ inputs.environment }}. Must be 'development' or 'staging'."
            exit 1
          fi

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # access full git history

      - uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 # v5.0.0
        with:
          uri: "https://github.com/go-task/task/releases/download/v3.49.1/task_linux_amd64.tar.gz"
          name: task
          version: v3.49.1

      - name: docker-build-with-task
        working-directory: ./docker
        # from root-dir-
        run: |
          task build-airflow-image
